# -*- coding: utf-8 -*-
"""function_assignment (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jU9n-1pRRpehk2lJQ80vIO3c7gmBc_LG
"""

#1
def subfields():
    subfields = ["machine learning", "neural learning", "vision", "robotics", "speech processing", "natural language processing"]
    print("Sub-field in AI:")
    for i in subfields:
        print(i)


subfields()

#2logic on odd even function#
num=int(input("enter the no"))
    if num%2==0:
        print("even no")
    else:
        print("odd no")

#2
def OddEven():
    num=int(input("enter the no"))
    if num%2==0:
        print("even no")
    else:
        print("odd no")

OddEven()

#3 logic of code
gender = input(str("Your gender: "))
age = int(input("Your age:"))
if age >= 18:
    print("Eligible for marriage")
else:
    print("Not eligible")

#5
def Eligible():
    gender = input(str("Your gender: "))
    age = int(input("Your age:"))
    if age >= 18:
        print("Eligible for marriage")
    else:
        print("Not eligible")

Eligible()

#4#
def percentage():
    dic ={'subject1': 23, 'subject2': 45, 'subject3': 34, 'subject4': 23, 'subject5': 23}
    total = int(dic['subject1']) + int(dic['subject2']) + int(dic['subject3']) +int(dic['subject4']) +int(dic['subject5'])
    percentage =float((total / 500) * 100)
    print(total)
    print(percentage)

percentage()

#5
def triangle():
    h=int(input("hieght"))
    b=int(input("weight"))
    hieght1=int(input())
    hieght2=int(input())
    area =(h*b)/2
    print("area of triangle:",area)
    print("hieght1:", hieght1)
    print("hieght2:", hieght2)
    print("breath:",b)
    perimeter=hieght1+hieght1+b
    print("perimeter of triangle:",perimeter)

triangle()

